import {
  Baby,
  Banknote,
  Bike,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  Car,
  Coffee,
  CreditCard,
  Dog,
  Dumbbell,
  Ellipsis,
  Film,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  HandCoins,
  HeartPulse,
  House,
  Landmark,
  Laptop,
  Music,
  PiggyBank,
  Plane,
  Receipt,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Stethoscope,
  TrendingUp,
  Utensils,
  Wallet,
  Wifi,
  Zap,
  type LucideIcon,
} from 'lucide-react'

/**
 * Icons users can assign to categories and wallets. Stored by name in the DB so the
 * icon set can change without a migration; unknown names fall back to Ellipsis.
 * Kept as an explicit list (not `import *`) so unused Lucide icons are tree-shaken.
 */
export const ICONS: Record<string, LucideIcon> = {
  utensils: Utensils,
  coffee: Coffee,
  bike: Bike,
  car: Car,
  bus: Bus,
  fuel: Fuel,
  plane: Plane,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  house: House,
  building: Building2,
  receipt: Receipt,
  zap: Zap,
  wifi: Wifi,
  smartphone: Smartphone,
  gamepad: Gamepad2,
  film: Film,
  music: Music,
  'heart-pulse': HeartPulse,
  stethoscope: Stethoscope,
  dumbbell: Dumbbell,
  'graduation-cap': GraduationCap,
  book: BookOpen,
  shirt: Shirt,
  scissors: Scissors,
  gift: Gift,
  baby: Baby,
  dog: Dog,
  'credit-card': CreditCard,
  'hand-coins': HandCoins,
  landmark: Landmark,
  briefcase: Briefcase,
  sparkles: Sparkles,
  laptop: Laptop,
  'trending-up': TrendingUp,
  wallet: Wallet,
  banknote: Banknote,
  'piggy-bank': PiggyBank,
  ellipsis: Ellipsis,
}

export const ICON_NAMES = Object.keys(ICONS)

export function iconFor(name: string): LucideIcon {
  return ICONS[name] ?? Ellipsis
}
